root: true
extends: [cheminfo-typescript, cheminfo-typescript/jsdoc]
parserOptions:
  project:
    - './packages/*/tsconfig.json'
    - './packages/*/tsconfig.test.json'
rules:
  'import/no-unresolved':
    - error
    - ignore: ['-analysis$']
      commonjs: true
